name: sass_builder
version: 1.1.0
authors:
- Luis Vargas <luisvargastijerino@gmail.com>
- Kevin Moore <kevmoo@github.com>
- Nicholas Shahan <nshahan@github.com>
homepage: https://github.com/dart-league/sass_builder
description: Transpile sass files using the "build" package.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  barback: ^0.15.2
  build: ^0.11.1
  build_barback: ^0.4.0+2
  build_runner: ^0.6.1
  logging: ^0.11.3
  package_resolver: ^1.0.2
  path: ^1.4.1
  sass: ^1.0.0-beta.2
  scratch_space: ^0.0.1
dev_dependencies:
  bootstrap_sass: 4.0.0-alpha.5+1
  build_test: ^0.9.1
  test: ^0.12.0
